env:
  RUBY_VERSION: 2.7.1
  POSTGRES_DB: postgres

# name of the workflow as it apears on GitHub
name: Rails tests
# Events that will trigger the workflow
on: [push, pull_request]
# All the tasks defined for this workflow
jobs:
  rubocop-test:
    # Name of the task
    name: Rubocop
    # OS to run tests on can also be macOS or WinServer2019
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-18.04
    # Define the instructions that prepare the OS and make it run tests
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      # install ruby
      - uses: actions/setup-ruby@v1
        with: 
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop For Rails
        run: gem install rubocop-rails
      - name: Check code
        run: rubocop
  
  rspec-test:
    name: RSpec
    # Jobs that must pass to run this one
    needs: rubocop-test
    runs-on: ubuntu-18.04
    # Services needed for these tests to run
    services:
      db:
        image: postgres:11@sha256:85d79cba2d4942dad7c99f84ec389a5b9cc84fb07a3dcd3aff0fb06948cdc03b
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with: 
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Create database
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
          RAILS_MASTER_KEY: $ {{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libpq-dev
          bundler exec rails db:create
          bundler exec rails db:migrate
          bundler exec rspec